// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc9z6Q75wI0gcodJBaVs8bJX8s1vqQ_90',
    appId: '1:420947970684:web:547c52749497457d0e17f9',
    messagingSenderId: '420947970684',
    projectId: 'tcc-partitura',
    authDomain: 'tcc-partitura.firebaseapp.com',
    storageBucket: 'tcc-partitura.firebasestorage.app',
    measurementId: 'G-TDKM4B290C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyuyzq-s5Tyx3io94Cc_LpmWBTNETfGQg',
    appId: '1:420947970684:android:56189746e540c4e20e17f9',
    messagingSenderId: '420947970684',
    projectId: 'tcc-partitura',
    storageBucket: 'tcc-partitura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwxF33MELMkIwhOrHKWdywMoNz3s5YwM',
    appId: '1:420947970684:ios:3870f141b942e2f00e17f9',
    messagingSenderId: '420947970684',
    projectId: 'tcc-partitura',
    storageBucket: 'tcc-partitura.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJwxF33MELMkIwhOrHKWdywMoNz3s5YwM',
    appId: '1:420947970684:ios:3870f141b942e2f00e17f9',
    messagingSenderId: '420947970684',
    projectId: 'tcc-partitura',
    storageBucket: 'tcc-partitura.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc9z6Q75wI0gcodJBaVs8bJX8s1vqQ_90',
    appId: '1:420947970684:web:83830ca7061830040e17f9',
    messagingSenderId: '420947970684',
    projectId: 'tcc-partitura',
    authDomain: 'tcc-partitura.firebaseapp.com',
    storageBucket: 'tcc-partitura.firebasestorage.app',
    measurementId: 'G-PWXPMVWNQ3',
  );
}
